[greeter]
background=/usr/share/backgrounds/shreeos/shreeos-calm-light.png
logo=/usr/share/pixmaps/shreeos-logo.svg
theme-name=Arc
icon-theme-name=Papirus
font-name=Inter 10
indicators=~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
