#!/usr/bin/env bash
# bootloader/scripts/install-grub-disk.sh — Install GRUB2 to a target installed disk
#
# Supports --boot-mode=both|uefi|bios. Installs UEFI (x86_64-efi to ESP)
# and/or BIOS (i386-pc to MBR/GPT) and generates grub.cfg with root UUID.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHREEOS_ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$SHREEOS_ROOT_DIR/build.conf" 2>/dev/null || true
source "$SHREEOS_ROOT_DIR/scripts/common.sh" 2>/dev/null || {
  shreeos_step() { echo "==> $1"; }
  shreeos_log() { echo "  -> $1"; }
  shreeos_ok() { echo "  [OK] $1"; }
  shreeos_warn() { echo "  [WARN] $1"; }
  shreeos_die() { echo "  [ERROR] $1" >&2; exit 1; }
  shreeos_require_cmd() { for c in "$@"; do command -v "$c" >/dev/null 2>&1 || { echo "Missing $c" >&2; exit 1; }; done; }
  lumen_die() { shreeos_die "$@"; }
  lumen_require_cmd() { shreeos_require_cmd "$@"; }
}

if [ $# -lt 2 ]; then
  shreeos_die "Usage: install-grub-disk.sh <target-root-mount> <disk-device> [--efi-dir=...] [--cmdline=...] [--boot-mode=both|uefi|bios]"
fi

TARGET="$1"
DISK="$2"
shift 2 || true

EFI_DIR="${TARGET}/boot/efi"
CMDLINE_EXTRA=""
BOOT_MODE="both"

for arg in "$@"; do
  case "$arg" in
    --efi-dir=*) EFI_DIR="${arg#*=}" ;;
    --cmdline=*) CMDLINE_EXTRA="${arg#*=}" ;;
    --boot-mode=*) BOOT_MODE="${arg#*=}" ;;
  esac
done

if [ ! -d "$TARGET" ]; then
  shreeos_die "Target mount directory '${TARGET}' does not exist."
fi
if [ ! -s "${TARGET}/boot/bzImage" ] || [ ! -s "${TARGET}/boot/initramfs.cpio.gz" ]; then
  shreeos_die "Target is missing /boot/bzImage or /boot/initramfs.cpio.gz; refusing to generate an unbootable GRUB configuration."
fi

shreeos_require_cmd grub-install blkid

shreeos_step "Installing GRUB2 (${BOOT_MODE}) to target disk ${DISK} (Target root: ${TARGET})"

mkdir -p "${TARGET}/boot/grub"
mkdir -p "${EFI_DIR}"

UEFI_SUCCESS=false
BIOS_SUCCESS=false

# 1. Install UEFI Bootloader (x86_64-efi)
if [ "$BOOT_MODE" = "both" ] || [ "$BOOT_MODE" = "uefi" ]; then
  shreeos_log "Installing GRUB for UEFI (x86_64-efi) into ${EFI_DIR}..."
  if grub-install \
      --target=x86_64-efi \
      --boot-directory="${TARGET}/boot" \
      --efi-directory="${EFI_DIR}" \
      --bootloader-id="${DISTRO_NAME:-ShreeOS}" \
      --removable \
      --recheck; then
    shreeos_ok "GRUB UEFI (x86_64-efi) installed successfully"
    UEFI_SUCCESS=true
  else
    if [ "$BOOT_MODE" = "uefi" ]; then
      shreeos_die "FATAL: grub-install for x86_64-efi failed during UEFI-only installation."
    else
      shreeos_warn "grub-install for x86_64-efi failed (grub-efi-amd64 may be missing or ESP not mounted)"
    fi
  fi
fi

# 2. Install BIOS Bootloader (i386-pc)
if [ "$BOOT_MODE" = "both" ] || [ "$BOOT_MODE" = "bios" ]; then
  shreeos_log "Installing GRUB for BIOS (i386-pc) onto ${DISK}..."
  if grub-install \
      --target=i386-pc \
      --boot-directory="${TARGET}/boot" \
      --recheck \
      "${DISK}"; then
    shreeos_ok "GRUB BIOS (i386-pc) installed successfully on ${DISK}"
    BIOS_SUCCESS=true
  else
    if [ "$BOOT_MODE" = "bios" ]; then
      shreeos_die "FATAL: grub-install for i386-pc failed during BIOS-only installation."
    else
      shreeos_warn "grub-install for i386-pc failed"
    fi
  fi
fi

if [ "$UEFI_SUCCESS" = false ] && [ "$BIOS_SUCCESS" = false ]; then
  shreeos_die "FATAL: Neither UEFI nor BIOS GRUB installation succeeded on ${DISK}."
fi

# 3. Detect Root UUID and Generate Target grub.cfg (Fail closed if missing)
shreeos_log "Discovering root filesystem UUID for ${TARGET}..."

TARGET_DEV=$(findmnt -n -o SOURCE "$TARGET" 2>/dev/null || echo "")
ROOT_UUID=""

if [ -n "$TARGET_DEV" ]; then
  ROOT_UUID=$(blkid -s UUID -o value "$TARGET_DEV" 2>/dev/null || echo "")
fi

if [ -z "$ROOT_UUID" ]; then
  if [ -b "${DISK}p3" ]; then
    ROOT_UUID=$(blkid -s UUID -o value "${DISK}p3" 2>/dev/null || echo "")
  elif [ -b "${DISK}3" ]; then
    ROOT_UUID=$(blkid -s UUID -o value "${DISK}3" 2>/dev/null || echo "")
  fi
fi

if [ -z "$ROOT_UUID" ]; then
  shreeos_die "CRITICAL BOOT ERROR: Could not determine filesystem UUID for root partition. Refusing to install unbootable fallback."
fi

cat > "${TARGET}/boot/grub/grub.cfg" <<EOF
# GRUB Configuration — Generated by ShreeOS installer
set default=0
set timeout=5

# Load video and graphics modules
insmod all_video
insmod font
insmod gfxterm
set gfxmode=auto
terminal_output gfxterm

# Filesystem modules
insmod gpt
insmod part_gpt
insmod part_msdos
insmod ext2
insmod fat

menuentry "${DISTRO_NAME:-ShreeOS} ${DISTRO_VERSION:-0.2.0-dev}" {
    echo "Loading Linux kernel..."
    search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
    linux /boot/bzImage root=UUID=${ROOT_UUID} ro quiet ${CMDLINE_EXTRA}
    echo "Loading initramfs..."
    initrd /boot/initramfs.cpio.gz
    echo "Booting ${DISTRO_NAME:-ShreeOS}..."
}

menuentry "${DISTRO_NAME:-ShreeOS} (Recovery Mode)" {
    echo "Loading Linux kernel in single-user recovery mode..."
    search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
    linux /boot/bzImage root=UUID=${ROOT_UUID} ro single shreeos.mode=recovery ${CMDLINE_EXTRA}
    initrd /boot/initramfs.cpio.gz
}

menuentry "${DISTRO_NAME:-ShreeOS} Previous Working State (SafeUpdate Rollback)" {
    search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
    linux /boot/bzImage root=UUID=${ROOT_UUID} ro single shreeos.rollback=1 ${CMDLINE_EXTRA}
    initrd /boot/initramfs.cpio.gz
}
EOF

shreeos_ok "Generated ${TARGET}/boot/grub/grub.cfg with Root UUID ${ROOT_UUID}"
