#!/usr/bin/env bash
# bootloader/scripts/install-grub-disk.sh — Install GRUB2 to a target installed disk
#
# Installs both UEFI (x86_64-efi to ESP) and BIOS (i386-pc to MBR/GPT) bootloaders
# onto the target installation disk and configures GRUB with proper root UUID.
#
# Usage:
#   bash bootloader/scripts/install-grub-disk.sh <target-mount> <disk-device> [--efi-dir=<path>] [--cmdline=...]
#
# Examples:
#   bash bootloader/scripts/install-grub-disk.sh /mnt /dev/sda
#   bash bootloader/scripts/install-grub-disk.sh /mnt /dev/nvme0n1 --efi-dir=/mnt/boot/efi
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHREEOS_ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$SHREEOS_ROOT_DIR/build.conf" 2>/dev/null || true
source "$SHREEOS_ROOT_DIR/scripts/common.sh" 2>/dev/null || {
  shreeos_step() { echo "==> $1"; }
  shreeos_log() { echo "  -> $1"; }
  shreeos_ok() { echo "  [OK] $1"; }
  shreeos_warn() { echo "  [WARN] $1"; }
  shreeos_die() { echo "  [ERROR] $1" >&2; exit 1; }
  shreeos_require_cmd() { for c in "$@"; do command -v "$c" >/dev/null 2>&1 || { echo "Missing $c" >&2; exit 1; }; done; }
  lumen_die() { shreeos_die "$@"; }
  lumen_require_cmd() { shreeos_require_cmd "$@"; }
}

if [ $# -lt 2 ]; then
  shreeos_die "Usage: install-grub-disk.sh <target-root-mount> <disk-device> [--efi-dir=...] [--cmdline=...]"
fi

TARGET="$1"
DISK="$2"
shift 2 || true

EFI_DIR="${TARGET}/boot/efi"
CMDLINE_EXTRA=""

for arg in "$@"; do
  case "$arg" in
    --efi-dir=*) EFI_DIR="${arg#*=}" ;;
    --cmdline=*) CMDLINE_EXTRA="${arg#*=}" ;;
  esac
done

if [ ! -d "$TARGET" ]; then
  shreeos_die "Target mount directory '${TARGET}' does not exist."
fi

shreeos_require_cmd grub-install

shreeos_step "Installing GRUB2 to target disk ${DISK} (Target root: ${TARGET})"

mkdir -p "${TARGET}/boot/grub"
mkdir -p "${EFI_DIR}"

UEFI_SUCCESS=false
BIOS_SUCCESS=false

# 1. Install UEFI Bootloader (x86_64-efi)
shreeos_log "Installing GRUB for UEFI (x86_64-efi) into ${EFI_DIR}..."
if grub-install \
    --target=x86_64-efi \
    --boot-directory="${TARGET}/boot" \
    --efi-directory="${EFI_DIR}" \
    --bootloader-id="${DISTRO_NAME:-ShreeOS}" \
    --removable \
    --recheck; then
  shreeos_ok "GRUB UEFI (x86_64-efi) installed successfully"
  UEFI_SUCCESS=true
else
  shreeos_warn "grub-install for x86_64-efi returned an error (grub-efi-amd64 may be missing on host or ESP not ready)"
fi

# 2. Install BIOS Bootloader (i386-pc)
shreeos_log "Installing GRUB for BIOS (i386-pc) onto ${DISK}..."
if grub-install \
    --target=i386-pc \
    --boot-directory="${TARGET}/boot" \
    --recheck \
    "${DISK}"; then
  shreeos_ok "GRUB BIOS (i386-pc) installed successfully on ${DISK}"
  BIOS_SUCCESS=true
else
  shreeos_warn "grub-install for i386-pc returned an error (grub-pc may be missing on host or non-block device)"
fi

if [ "$UEFI_SUCCESS" = false ] && [ "$BIOS_SUCCESS" = false ]; then
  shreeos_die "FATAL: Both UEFI and BIOS GRUB installations failed on ${DISK}."
fi

# 3. Detect Root UUID and Generate Target grub.cfg
shreeos_log "Generating GRUB configuration for installed system"

ROOT_UUID=""
# Attempt to find UUID for the root filesystem
if command -v blkid >/dev/null 2>&1; then
  # Find partition mounted at $TARGET
  TARGET_DEV=$(findmnt -n -o SOURCE "$TARGET" 2>/dev/null || echo "")
  if [ -n "$TARGET_DEV" ]; then
    ROOT_UUID=$(blkid -s UUID -o value "$TARGET_DEV" 2>/dev/null || echo "")
  fi
fi

ROOT_PARAM="root=UUID=${ROOT_UUID}"
if [ -z "$ROOT_UUID" ]; then
  # Fallback if blkid or mountpoint lookup isn't available
  ROOT_PARAM="root=/dev/sda3"
fi

cat > "${TARGET}/boot/grub/grub.cfg" <<EOF
# GRUB Configuration — Generated by ShreeOS installer
set default=0
set timeout=5

# Load video and graphics modules
insmod all_video
insmod font
insmod gfxterm
set gfxmode=auto
terminal_output gfxterm

# Filesystem modules
insmod gpt
insmod part_gpt
insmod part_msdos
insmod ext2
insmod fat

menuentry "${DISTRO_NAME:-ShreeOS} ${DISTRO_VERSION:-0.1.0-dev}" {
    echo "Loading Linux kernel..."
    search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
    linux /boot/bzImage ${ROOT_PARAM} ro quiet ${CMDLINE_EXTRA}
    if [ -f /boot/rootfs.cpio.gz ]; then
        echo "Loading initramfs..."
        initrd /boot/rootfs.cpio.gz
    fi
    echo "Booting ${DISTRO_NAME:-ShreeOS}..."
}

menuentry "${DISTRO_NAME:-ShreeOS} (Recovery / Single-User Mode)" {
    echo "Loading Linux kernel in single-user mode..."
    search --no-floppy --fs-uuid --set=root ${ROOT_UUID}
    linux /boot/bzImage ${ROOT_PARAM} ro single ${CMDLINE_EXTRA}
    if [ -f /boot/rootfs.cpio.gz ]; then
        initrd /boot/rootfs.cpio.gz
    fi
}
EOF

shreeos_ok "Generated ${TARGET}/boot/grub/grub.cfg (Root UUID: ${ROOT_UUID:-none})"
