---
userGroup: users
defaultGroups:
    - cdrom
    - sudo
    - audio
    - video
    - plugdev
    - netdev
    - lpadmin
    - scanner
    - bluetooth
sudoersGroup: sudo
setRootPassword: false

passwordRequirements:
    nonempty: true
    minLength: 8
    maxLength: -1
    libpwquality:
        - minlen=8
        - minclass=2
