---
modules-search: [ local, /usr/lib/calamares/modules ]
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - luksbootkeyfile
  - dpkg-unsafe-io
  - sources-media
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader-config
  - grubcfg
  - bootloader
  - packages
  - plymouthcfg
  - initramfscfg
  - initramfs
  - dpkg-unsafe-io-undo
  - sources-media-unmount
  - sources-final
  - umount
- show:
  - finished

branding: shreeos
prompt-install: true
dont-chroot: false
